### ISSUE TITLE
Post-positconf checklist

### ISSUE THREAD

**Issue by jimjam-slam** [qmd-lab/closeread#18]
- [ ] **Bug:** OJS block counter should return to `null` when you scroll back up before the first step, not go to `-1`
- [ ] **Bug:** Inline image syntax with `cr-id` no longer is detected as sticky when there is a caption.
- [x] **Check:** do we support multiple elements as comma-separated lists for `cr-from` and `cr-to`?
  - Might be appropriate to put a demo together for this. I believe I said in [#13](https://github.com/quarto-lab/close-read/issues/13#issuecomment-1685807812) that I'd implemented this but not tested it
- [ ] **Image pan/zoom**
- [x] **Code and poem line highlighting**
- [ ] **Auto animate**
- [ ] **Additional customisability** through YAML frontmatter. For example:
  - Scrollama offset 
  - Sidebar Width / Left-Right swap
  - What's the balance between YAML options vs CSS customization?
- [ ] **Mobile layout**
  - We've switched from the old flexbox-based layout to a grid-based one
  - Currently work on the mobile layout using grid is in #24, but we need to resolve some issues with poem width
  - Once that's resolved, we will probably want to add in some more grid columns to add gutters, positioning options, etc.

**Comment by jimjam-slam** [comment]
Next priorities:

- Switch to [Bootstrap CSS Grid](https://getbootstrap.com/docs/5.1/layout/css-grid/#responsive)
  - Does sticky content stay on top?
  - Additional gutter elements
  - May need to change `.cr-section` from `.column-page` to `.column-screen` ✅

- Transforming non-image sticky blocks (or maybe just all of them) with JS

**Comment by jimjam-slam** [comment]
Something I found in the [Quarto 1.4 pre-release docs](https://quarto.org/docs/prerelease/1.4/crossref.html) that I think is relevant to our image processing:

> Images by themselves used to have a surrounding paragraph; they no longer do.

(I'm starting to be able to type with two hands again! 🥳)

**Comment by jimjam-slam** [comment]
And a second thing actually:

> All cross-referenceable elements use the figure HTML element with class `quarto-float`.

**Comment by andrewpbray** [comment]
Oh, the dramatic arc of medical recovery in two emojis =(

That's a good spot of the pre-release notes! I bet they'll swap out `Para` with `Figure` in both pandoc and html. Will probably make things a bit easier for us.

Speaking of 1.4, have you installed it yet? I haven't yet because I'm afraid of messing up all the course materials right here at the end of the semester, but I may in a week or two when things wrap up. In general, how do you manage different installs like this?

**Comment by jimjam-slam** [comment]
I've been running 1.4, but I haven't worked out a way to manage multiple installs yet! Maybe I'll just alias the pre-release one in my terminal, since you essentially just clone and run that...

**Comment by jimjam-slam** [comment]
Dropping a link to this comment that relates to our image testing!

https://github.com/quarto-dev/quarto-cli/discussions/9310#discussioncomment-9056156

Apparently if you append a backslash `\` to a Markdown image, it renders as inline...

**Comment by jimjam-slam** [comment]
## For Postit-conf 2024

Implement `focuson` and `focuswith` for:

- [ ] Poem:
  - on: line number, sets of line numbers, or span / sets of spans:
  - with: zoom, highlight
- [ ] Image:
  - on: x,y, or ul, ll, lr, ur
  - with: zoom, highlight
- [ ] Code:
  - on: line number, sets of line numbers, or span / sets of spans:
  - with: zoom, highlight

- [ ] Sizing config
  - [ ] Sketch grid size tracks for mobile/tablet/desktop
  - [ ] Add YAML options

- [ ] Build demos:
  - [ ] Explaining code
  - [ ] Observable or other reactive visuals
  - [ ] Poem or image

## After Posit-conf 2024

- [ ] Math
- [ ] animate (a la reveals)_
- [ ] Full-bleed sticky content

**Comment by andrewpbray** [comment]
Separate issues and PRs have worked on each one of these elements and most of them are now done or posted as individual issues so I'll close this.
